export const dom = {
  loginModal: document.getElementById("loginModal") as any,
  modalTitle: document.getElementById("modalTitle") as any,
  modalUserName: document.getElementById("modalUserName") as any,
  modalPassword: document.getElementById("modalPassword") as any,
  modalSubmit: document.getElementById("modalSubmit") as any,
  modalModeToggle: document.getElementById("modalModeToggle") as any,
  logoutBtn: document.getElementById("logoutBtn") as any,
  currentUser: document.getElementById("currentUser") as any,
  modalError: document.getElementById("modalError") as any,
  createFolderBtn: document.getElementById("createFolderBtn") as any,
  folderNameInput: document.getElementById("folderName") as any,
  createFileBtn: document.getElementById("createFileBtn") as any,
  fileNameInput: document.getElementById("fileNameInput") as any,
  uploadBtn: document.getElementById("uploadBtn") as any,
  folderInput: document.getElementById("folderInput") as any,
  folderInputLabel: document.getElementById("folderInputLabel") as any,
  uploadFolderBtn: document.getElementById("uploadFolderBtn") as any,
  folderInputName: document.getElementById("folderInputName") as any,
  fileInput: document.getElementById("fileInput") as any,
  fileInputName: document.getElementById("fileInputName") as any,
  errorMessage: document.getElementById("errorMessage") as any,
  explorerPath: document.getElementById("explorerPath") as any,
  fileList: document.getElementById("file-list") as any,
  fileContentTitle: document.getElementById("fileContentTitle") as any,
  fileContentBody: document.getElementById("fileContentBody") as any,
  fileContentPath: document.getElementById("fileContentPath") as any,
  fileContentTextarea: document.getElementById("fileContentTextarea") as any,
  editBtn: document.getElementById("editBtn") as any,
  shareBtn: document.getElementById("shareBtn") as any,
  saveBtn: document.getElementById("saveBtn") as any,
  cancelBtn: document.getElementById("cancelBtn") as any,
  metadataBox: document.getElementById("file-info-box") as any,
  historyBox: document.getElementById("file-history-box") as any,
  explorerSearchToggle: document.getElementById("explorerSearchToggle") as any,
  explorerSearchInput: document.getElementById("explorerSearchInput") as any,
  explorerSearchWrap: document.getElementById("explorerSearchWrap") as any,
  binBtn: document.getElementById("binBtn") as any,
  binPanel: document.getElementById("binPanel") as any,
  binCloseBtn: document.getElementById("binCloseBtn") as any,
  binItemsList: document.getElementById("binItemsList") as any,
};

export const state = {
  authMode: "login" as "login" | "register",
  connection: null as any,
  currentPath: "",
  currentFileName: "",
  activeHistoryFileName: "",
  activeHistoryEntries: [] as any[],
  historyCursor: -1,
  isEditMode: false,
  currentFileIsEditable: false,
  errorMessageTimeoutId: null as any,
  modalErrorTimeoutId: null as any,
  activePreviewObjectUrl: null as string | null,
  originalContent: null as string | null,
  searchQuery: "",
  searchVisible: false,
  allFiles: {} as Record<string, { file: boolean }>,
};

export const MESSAGE_TIMEOUT_MS = 5000;
export const DEFAULT_PREVIEW_TEXT = "Select a file to preview its content.";
